config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root "contributes#index"
  resources :contributes, only: [:index, :new, :create, :show] do
    resources :contribute_likes, only: [:create, :destroy]
    collection do
      resources :mangas, only: :index
      resources :columns, only: :index
      resources :novels, only: :index
      resources :photos, only: :index
      resources :musics, only: :index
      resources :businesses, only: :index
      resources :lifestyles, only: :index
      resources :techs, only: :index
      resources :entertainments, only: :index
      resources :pickups, only: :index
      resources :categories, only: :index
      resources :hashtags, only: :index
      resources :helps, only: :index
    end
  end
  resources :hashtags, param: :hashtag, path: '/', only: :show do
    collection do
      get 'popular'
    end
  end
  resources :users, only: [:index, :show]
  resources :comments, only: [:create, :destroy, :edit, :update] do
    resources :comment_likes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :contribute
  has_many :comment_likes, dependent: :destroy
  def like_user(user_id)
    comment_likes.find_by(user_id: user_id)
  end
end

app/models/comment_like.rb
class CommentLike < ApplicationRecord
  belongs_to :user
  belongs_to :comment, counter_cache: :likes_count
end

app/models/contribute.rb
class Contribute < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many :contribute_likes, dependent: :destroy
  has_many :contribute_tags, through: :contributes_to_tags
  has_many :contributes_to_tags, dependent: :destroy
  mount_uploader :image, ImageUploader
  def like_user(user_id)
    contribute_likes.find_by(user_id: user_id)
  end

  def before_contribute
    Contribute.order("created_at DESC").find_by("created_at <= ? and id <?",created_at, id)
  end

  def next_contribute
    Contribute.order(created_at: :desc, id: :desc).where("created_at >= ? and id > ?", created_at, id).reverse.first
  end
end

app/models/contribute_like.rb
class ContributeLike < ApplicationRecord
  belongs_to :user
  belongs_to :contribute, counter_cache: :likes_count
end

app/models/contribute_tag.rb
class ContributeTag < ApplicationRecord
  has_many :contributes, through: :contributes_to_tags
  has_many :contributes_to_tags, dependent: :destroy
end

app/models/contributes_to_tag.rb
class ContributesToTag < ApplicationRecord
  belongs_to :contribute
  belongs_to :contribute_tag
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :contributes
  has_many :comments
  has_many :follows
  validates :agreement, acceptance: true
end

app/controllers/columns_controller.rb
class ColumnsController < ApplicationController
  before_action :get_category

  private
  def get_category
    @category= params[:controller]
  end
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  before_action :get_category

  private
  def get_category
    @category= params[:controller]
  end
end

app/controllers/mangas_controller.rb
class MangasController < ApplicationController
  before_action :get_category

  private
  def get_category
    @category= params[:controller]
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :get_category

  private
  def get_category
    @category= params[:controller]
  end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :get_category

  private
  def get_category
    @category= params[:controller]
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :get_category

  private
  def get_category
    @category= params[:controller]
  end
end

app/controllers/pickups_controller.rb
class PickupsController < ApplicationController
  before_action :get_category

  private
  def get_category
    @category= params[:controller]
  end
end

app/controllers/techs_controller.rb
class TechsController < ApplicationController
  before_action :get_category

  private
  def get_category
    @category= params[:controller]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
require 'navigation_helper.rb'

module ApplicationHelper
  include NavigationHelper
end
end

app/helpers/navigation_helper.rb
module NavigationHelper

  def header_top_partial_path
    if user_signed_in?
      'layouts/header_top/signed_in_header'
    else
      'layouts/header_top/non_signed_in_header'
    end
  end

end

app/views/layouts/header_top/_non_signed_in_header.haml
%li.inline
  = link_to "ログイン", new_user_session_path, class: "login__button"
%li.inline
  = link_to "新規登録", new_user_registration_path, class: "regist__button"
%li.inline
  = image_tag "search_button", class: "search__button"

app/views/layouts/header_top/_signed_in_header.haml
%li.inline
  = image_tag "search_button", class: "search__button"
%li.inline
  = image_tag "notification_button", class: "notification__button"
%li.inline
  = image_tag "#{current_user.image}", class: "user__image"
%li.inline.new__post__create
  = image_tag "pen_button", class: "pen__button"
  %p.new__post ノートを投稿
.new__post__select
  %ul.new__post__list
    %li.inline.new__post__element
      = link_to new_contribute_path, class: "new__post__icon" do
        = image_tag "make_text"
        %p.new__post__text テキスト
    %li.inline.new__post__element
      = link_to helps_path, class: "new__post__icon" do
        = image_tag "make_image"
        %p.new__post__text イメージ
    %li.inline.new__post__element
      = link_to helps_path, class: "new__post__icon" do
        = image_tag "make_talk"
        %p.new__post__text トーク
    %li.inline.new__post__element
      = link_to helps_path, class: "new__post__icon" do
        = image_tag "make_sound"
        %p.new__post__text サウンド
    %li.inline.new__post__element
      = link_to helps_path, class: "new__post__icon" do
        = image_tag "make_movie"
        %p.new__post__text ムービー